# Exported from Render on 2024-05-03T09:45:44Z
services:
- type: web
  name: cliart
  runtime: node
  repo: https://github.com/antoniodin74/cliart
  plan: free
  envVars:
  - key: JWT_SECRET
    sync: false
  - key: MONGODB_URI
    sync: false
  region: frankfurt
  buildCommand: npm install
  startCommand: node index.js
  autoDeploy: false
version: "1"
